---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env-conf-{{ include "tyk-hybrid.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-hybrid.fullname" . }}
    chart: {{ include "tyk-hybrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  TYK_GW_LISTENPORT: "{{ .Values.gateway.containerPort }}"
  # Lagacy support for Redis Cluster driver. Driver dropped in v3.0.0.
  REDIGOCLUSTER_SHARDCOUNT: "128"
  TYK_GW_STORAGE_ADDRS: {{ include "tyk-hybrid.redis_url" . | quote }}
  TYK_GW_STORAGE_ENABLECLUSTER: "{{ default "false" .Values.redis.enableCluster }}"
  TYK_GW_STORAGE_DATABASE: "{{ default "0" .Values.redis.storage.database }}"
  TYK_GW_STORAGE_USESSL: "{{ default "false" .Values.redis.useSSL }}"
  TYK_GW_HTTPSERVEROPTIONS_USESSL: "{{ .Values.gateway.tls }}"
  TYK_GW_SLAVEOPTIONS_CONNECTIONSTRING: "{{ .Values.gateway.rpc.connString }}"
  TYK_GW_SLAVEOPTIONS_USESSL: "{{ .Values.gateway.rpc.useSSL }}"
  TYK_GW_SLAVEOPTIONS_BINDTOSLUGSINSTEADOFLISTENPATHS: "{{ default "false" .Values.gateway.rpc.bindToSlugs }}"
  TYK_GW_SLAVEOPTIONS_SSLINSECURESKIPVERIFY: "{{ .Values.gateway.rpc.sslInsecureSkipVerify }}"
  {{- if .Values.gateway.rpc.groupId }}
  TYK_GW_SLAVEOPTIONS_GROUPID: "{{ .Values.gateway.rpc.groupId }}"
  {{- end }}
  # Enable backward compatibility to chart 0.5.1.
  {{- if or .Values.gateway.sharding .Values.enableSharding }}
  {{- if .Values.gateway.sharding }}
  TYK_GW_DBAPPCONFOPTIONS_NODEISSEGMENTED: "{{ .Values.gateway.sharding.enabled }}"
  {{- else }}
  TYK_GW_DBAPPCONFOPTIONS_NODEISSEGMENTED: "{{ .Values.enableSharding }}"
    {{- end }}
  {{- end }}
  # Enable backward compatibility to chart 0.5.1.
  {{- if or .Values.gateway.sharding .Values.enableSharding }}
  {{- if .Values.gateway.sharding }}
  TYK_GW_DBAPPCONFOPTIONS_TAGS: "{{ .Values.gateway.sharding.tags }}"
  {{- else }}
  TYK_GW_DBAPPCONFOPTIONS_TAGS: "{{ .Values.gateway.tags }}"
  {{- end }}
  {{- end }}
  # Default Settings
  TYK_GW_TEMPLATEPATH: "/opt/tyk-gateway/templates"
  TYK_GW_TYKJSPATH: "/opt/tyk-gateway/js/tyk.js"
  TYK_GW_MIDDLEWAREPATH: "/mnt/tyk-gateway/middleware"
  TYK_GW_USEDBAPPCONFIGS: "false"
  TYK_GW_APPPATH: "/mnt/tyk-gateway/apps"
  TYK_GW_ENABLEANALYTICS: "true"
  TYK_GW_ANALYTICSCONFIG_TYPE: "rpc"
  TYK_GW_STORAGE_TYPE: "redis"
  TYK_GW_AUTHOVERRIDE_FORCEAUTHPROVIDER: "true"
  TYK_GW_AUTHOVERRIDE_AUTHPROVIDER_STORAGEENGINE: "rpc"
  TYK_GW_SLAVEOPTIONS_USERPC: "true"
  TYK_GW_SLAVEOPTIONS_RPCPOOLSIZE: "20"
  TYK_GW_SLAVEOPTIONS_ENABLERPCCACHE: "true"
  TYK_GW_ENABLENONTRANSACTIONALRATELIMITER: "true"
  TYK_GW_ENABLESENTINELRATELIMITER: "false"
  TYK_GW_ALLOWMASTERKEYS: "false"
  TYK_GW_POLICIES_POLICYSOURCE: "rpc"
  TYK_GW_POLICIES_POLICYRECORDNAME: "tyk_policies"
  TYK_GW_HASHKEYS: "true"
  TYK_GW_HASHKEYFUNCTION: "murmur128"
  TYK_GW_CLOSECONNECTIONS: "false"
  TYK_GW_HTTPSERVEROPTIONS_ENABLEWEBSOCKETS: "true"
  TYK_GW_HTTPSERVEROPTIONS_SERVERNAME: "*"
  TYK_GW_HTTPSERVEROPTIONS_MINVERSION: "771"
  TYK_GW_ALLOWINSECURECONFIGS: "true"
  TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS: "true"
  TYK_GW_ENABLEBUNDLEDOWNLOADER: "false"
  TYK_GW_GLOBALSESSIONLIFETIME: "100"
  TYK_GW_FORCEGLOBALSESSIONLIFETIME: "false"
  TYK_GW_MAXIDLECONNSPERHOST: "500"
  TYK_GW_ENABLECUSTOMDOMAINS: "true"
  TYK_GW_PIDFILELOCATION: "/mnt/tyk-gateway/tyk.pid"
  {{- if .Values.gateway.extraEnvs }}
  {{- range $envVar := .Values.gateway.extraEnvs }}
  {{ $envVar.name }}: "{{ $envVar.value }}"
  {{- end }} 
  {{- end }}
