{{- if .Values.gateway.enabled -}}
apiVersion: apps/v1
kind: {{ .Values.gateway.kind }}
metadata:
  name: gateway-{{ include "tyk-pro.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if eq .Values.gateway.kind "Deployment" }}
  replicas: {{ .Values.gateway.replicaCount }}
{{- end }}
  minReadySeconds: 10
{{- if eq .Values.gateway.kind "Deployment" }}
  strategy:
{{- else }}
  updateStrategy:
{{- end }}
{{- if ((.Values.gateway.strategy).type) }}
    type: {{ .Values.gateway.strategy.type }}
{{- else }}
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
{{- if eq .Values.gateway.kind "Deployment" }}
      maxSurge: 2
{{- end }}
      maxUnavailable: 1
{{- end }}
  selector:
    matchLabels:
      app: gateway-{{ include "tyk-pro.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      # Enable backward compatibility to chart 0.8.1.
      {{- if or .Values.gateway.enableIstioIngress .Values.enableIstioIngress }}
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "{{ .Values.gateway.containerPort}}"
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/excludeOutboundPorts: "{{ .Values.dash.containerPort }}"
        traffic.sidecar.istio.io/includeOutboundPorts: ""
      {{- end }}
      labels:
        app: gateway-{{ include "tyk-pro.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-gateway.yaml") . | sha256sum }}
    spec:
{{- if .Values.gateway.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.gateway.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.gateway.tolerations }}
      tolerations:
{{ toYaml .Values.gateway.tolerations | indent 8 }}
{{- end }}
{{- if .Values.gateway.affinity }}
      affinity:
{{ toYaml .Values.gateway.affinity | indent 8 }}
{{- end }}
      containers:
      - name: gateway-{{ .Chart.Name }}
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        envFrom:
        - configMapRef:
            name: gateway-env-conf-{{ include "tyk-pro.fullname" . }}
        env:
        - name: TYK_GW_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
              key: APISecret
        - name: TYK_GW_NODESECRET
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
              key: APISecret
        - name: TYK_GW_STORAGE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-pro.fullname" . }} {{ end}}
              key: redisPass
        command: ["/opt/tyk-gateway/tyk", "--conf=/etc/tyk-gateway/tyk.conf"]
        workingDir: /opt/tyk-gateway
        ports:
        - containerPort: {{ .Values.gateway.containerPort }}
        {{- if .Values.gateway.control.enabled }}
        - containerPort: {{ .Values.gateway.control.containerPort }}
        {{- end }}
        resources:
{{ toYaml .Values.gateway.resources | indent 12 }}
        volumeMounts:
          {{- if .Values.dash.tls }}
          - name: {{.Values.certificates.caConfigMapName}}
            mountPath: /etc/ssl/certs/{{.Values.certificates.caBundleFileName}}
            subPath: {{.Values.certificates.caBundleFileName}}
            readOnly: false
          {{- end }}
          - name: tyk-mgmt-gateway-conf
            mountPath: /etc/tyk-gateway
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
          - name: {{ .Release.Name }}-default-cert
            mountPath: /etc/certs
          {{- if .Values.gateway.certificates }}
          {{- range $i, $certset := .Values.gateway.certificates }}
          - name: tyk-gw-certs-crt-{{ $i }}
            mountPath: /etc/certs/crts
          - name: tyk-gw-certs-key-{{ $i }}
            mountPath: /etc/certs/keys
          {{- end }}
          {{- end }}
          {{- if .Values.gateway.mounts }}
          {{- range $secret := .Values.gateway.mounts }}
          - name: {{ $.Release.Name }}-gateway-secret-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
          {{- end }}
          {{- end }}
        livenessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.gateway.tls }}S{{ end }}"
            path: /hello
            {{- if and .Values.gateway.control.enabled (or (semverCompare "^3.2.x" (include "tyk-pro.gateway-version" . )) (semverCompare ">=3.0.4 < 3.1.0" (include "tyk-pro.gateway-version" .))) }}
            port: {{ .Values.gateway.control.containerPort }}
            {{- else }}
            port: {{ .Values.gateway.containerPort }}
            {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: "HTTP{{ if .Values.gateway.tls }}S{{ end }}"
            path: /hello
            {{- if and .Values.gateway.control.enabled (or (semverCompare "^3.2.x" (include "tyk-pro.gateway-version" . )) (semverCompare ">=3.0.4 < 3.1.0" (include "tyk-pro.gateway-version" .))) }}
            port: {{ .Values.gateway.control.containerPort }}
            {{- else }}
            port: {{ .Values.gateway.containerPort }}
            {{- end }}
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        {{- if .Values.dash.tls }}
        - name: {{.Values.certificates.caConfigMapName}}
          configMap:
            name: {{.Values.certificates.caConfigMapName}}
        {{- end }}
        - name: tyk-mgmt-gateway-conf
          configMap:
            name: mgmt-gateway-conf-{{ include "tyk-pro.fullname" . }}
            items:
              - key: tyk_mgmt.conf
                path: tyk.conf
        - name: tyk-scratch
          emptyDir: {}
        - name: {{ .Release.Name }}-default-cert
          secret:
            secretName: {{ .Release.Name }}-default-cert
        {{- if .Values.gateway.certificates }}
        {{- range $i, $certset := .Values.gateway.certificates }}
        - name: tyk-gw-certs-crt-{{ $i }}
          secret:
            secretName: {{ $certset.certSecret }}
        - name: tyk-gw-certs-key-{{ $i }}
          secret:
            secretName: {{ $certset.keySecret }}
        {{- end }}
        {{- end }}
        {{- if .Values.gateway.mounts }}
        {{- range $secret := .Values.gateway.mounts }}
        - name: {{ $.Release.Name }}-gateway-secret-{{ $secret.name }}
          secret:
            secretName: {{ $.Release.Name }}-gateway-secret-{{ $secret.name }}
        {{- end }}
        {{- end }}
{{- end }}
