{{- if .Values.dash.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc-{{ include "tyk-pro.fullname" . }}
  labels:
    app: dashboard-svc-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.dash.service.port }}
    targetPort: {{ .Values.dash.containerPort }}
    {{- if .Values.dash.service.nodePort }}
    nodePort: {{ .Values.dash.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  type: {{ .Values.dash.service.type }}
  selector:
    app: dashboard-{{ include "tyk-pro.fullname" . }}
    release: {{ .Release.Name }}
{{- end}} 
