{{- if .Values.pump.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-env-conf-{{ include "tyk-headless.fullname" . }}
  labels:
    app: pump-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  - name: TYK_PMP_OMITCONFIGFILE
    value: "true"
  - name: TYK_PMP_ANALYTICSSTORAGETYPE
    value: "redis"
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_TYPE
    value: "redis"
  {{- if and .Values.redis.host .Values.redis.port }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS
    value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
  {{- else }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS
    value: "{{ join "," .Values.redis.addrs }}"
  {{- end }}
  {{ if .Values.redis.enableSentinel }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
    value: "{{- .Values.redis.masterName -}}"
  {{ else if .Values.redis.enableCluster }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
    value: "true"
  {{ else }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
    value: ""
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
    value: "false"
  {{ end }}
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_DATABASE
    value: "{{ .Values.redis.storage.database }}"
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_REDISUSESSL
    value: "{{ default "false" .Values.redis.useSSL }}"
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MAXIDLE
    value: "2000"
  - name: TYK_PMP_ANALYTICSSTORAGECONFIG_MAXACTIVE
    value: "4000"
  - name: TYK_PMP_PURGEDELAY
    value: "4"
  {{ if eq "postgres" (include "tyk-headless.backend" .) }}
  - name: TYK_PMP_PUMPS_MAIN_TYPE
    value: "sql"
  - name: TYK_PMP_PUMPS_MAIN_META_TYPE
    value: "postgres"
  - name: TYK_PMP_PUMPS_MAINAGG_TYPE
    value: "sql_aggregate"
  - name: TYK_PMP_PUMPS_MAINAGG_META_TYPE
    value: "postgres"
  - name: TYK_PMP_UPTIMEPUMPCONFIG_UPTIMETYPE
    value: "sql"
  - name: TYK_PMP_UPTIMEPUMPCONFIG_TYPE
    value: "postgres"
  {{ else if eq "mongo" (include "tyk-headless.backend" .) }}
  - name: TYK_PMP_PUMPS_MAIN_TYPE
    value: "mongo"
  - name: TYK_PMP_PUMPS_MAIN_META_MONGOUSESSL
    value: "{{ default "false" .Values.mongo.useSSL }}"
  - name: TYK_PMP_PUMPS_MAIN_META_COLLECTIONNAME
    value: "tyk_analytics_headless"
  - name: TYK_PMP_PUMPS_MAINAGG_TYPE
    value: "mongo-pump-aggregate"
  - name: TYK_PMP_PUMPS_MAINAGG_META_MONGOUSESSL
    value:  "{{ default "false" .Values.mongo.useSSL }}"
  - name: TYK_PMP_PUMPS_MAINAGG_META_USEMIXEDCOLLECTION
    value: "true"
  - name: TYK_PMP_UPTIMEPUMPCONFIG_COLLECTIONNAME
    value: "tyk_uptime_analytics_headless"
  {{ end }}
  # Legacy support for Redis Cluster driver. Driver dropped in v3.0.0.
  - name: REDIGOCLUSTER_SHARDCOUNT
    value: "128"
  {{- if .Values.pump.extraEnvs }}
  {{- range $envVar := .Values.pump.extraEnvs }}
  {{ $envVar.name }}: "{{ $envVar.value }}"
  {{- end }} 
  {{- end }}
{{- end }}
