---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env-conf-{{ include "tyk-headless.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  TYK_GW_LISTENPORT: "{{ .Values.gateway.containerPort }}"
  {{- if .Values.gateway.control.enabled }}
  TYK_GW_CONTROLAPIPORT: "{{ .Values.gateway.control.containerPort }}"
  {{- end }}
  # Lagacy support for Redis Cluster driver. Driver dropped in v3.0.0.
  REDIGOCLUSTER_SHARDCOUNT: "128"
  TYK_GW_STORAGE_ADDRS: {{ include "tyk-headless.redis_url" . | quote }}
  {{ if .Values.redis.enableSentinel }}
  TYK_GW_STORAGE_MASTERNAME: "{{- .Values.redis.masterName -}}"
 {{ else if .Values.redis.enableCluster }}
  TYK_GW_STORAGE_ENABLECLUSTER: "true"
 {{ else }}
  TYK_GW_STORAGE_MASTERNAME: ""
  TYK_GW_STORAGE_ENABLECLUSTER: "false"
 {{ end }}
  TYK_GW_STORAGE_DATABASE: "{{ default "0" .Values.redis.storage.database }}"
  TYK_GW_STORAGE_USESSL: "{{ default "false" .Values.redis.useSSL }}"
  TYK_GW_HTTPSERVEROPTIONS_USESSL: "{{ .Values.gateway.tls }}"
  TYK_GW_ENABLEANALYTICS: "{{ .Values.pump.enabled }}"
  # Default Settings
  TYK_GW_TEMPLATEPATH: "/opt/tyk-gateway/templates"
  TYK_GW_TYKJSPATH: "/opt/tyk-gateway/js/tyk.js"
  TYK_GW_MIDDLEWAREPATH: "/mnt/tyk-gateway/middleware"
  TYK_GW_USEDBAPPCONFIGS: "false"
  TYK_GW_APPPATH: "/mnt/tyk-gateway/apps"
  TYK_GW_ANALYTICSCONFIG_TYPE: ""
  TYK_GW_STORAGE_TYPE: "redis"
  TYK_GW_ENABLENONTRANSACTIONALRATELIMITER: "true"
  TYK_GW_ENABLESENTINELRATELIMITER: "false"
  TYK_GW_ALLOWMASTERKEYS: "false"
  TYK_GW_POLICIES_POLICYSOURCE: "file"
  TYK_GW_POLICIES_POLICYRECORDNAME: "/mnt/tyk-gateway/policies/policies.json"
  TYK_GW_HASHKEYS: "true"
  TYK_GW_HASHKEYFUNCTION: "murmur128"
  TYK_GW_CLOSECONNECTIONS: "false"
  TYK_GW_HTTPSERVEROPTIONS_ENABLEWEBSOCKETS: "true"
  TYK_GW_HTTPSERVEROPTIONS_SERVERNAME: "*"
  TYK_GW_HTTPSERVEROPTIONS_MINVERSION: "771"
  TYK_GW_ALLOWINSECURECONFIGS: "true"
  TYK_GW_ENABLEHASHEDKEYSLISTING: "true"
  TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS: "true"
  TYK_GW_ENABLEBUNDLEDOWNLOADER: "false"
  TYK_GW_GLOBALSESSIONLIFETIME: "100"
  TYK_GW_FORCEGLOBALSESSIONLIFETIME: "false"
  TYK_GW_MAXIDLECONNSPERHOST: "500"
  TYK_GW_ENABLECUSTOMDOMAINS: "true"
  TYK_GW_PIDFILELOCATION: "/mnt/tyk-gateway/tyk.pid"
  {{- if .Values.gateway.extraEnvs }}
  {{- range $envVar := .Values.gateway.extraEnvs }}
  {{ $envVar.name }}: "{{ $envVar.value }}"
  {{- end }} 
  {{- end }}
