{{- if .Values.pump.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-{{ include "tyk-headless.fullname" . }}
  labels:
    app: pump-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pump.replicaCount }}
  selector:
    matchLabels:
      app: pump-{{ include "tyk-headless.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pump-{{ include "tyk-headless.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.pump.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.pump.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.pump.tolerations }}
      tolerations:
{{ toYaml .Values.pump.tolerations | indent 8 }}
{{- end }}
{{- if .Values.pump.affinity }}
      affinity:
{{ toYaml .Values.pump.affinity | indent 8 }}
{{- end }}
      containers:
      - name: pump-{{ .Chart.Name }}
        image: "{{ .Values.pump.image.repository }}:{{ .Values.pump.image.tag }}"
        imagePullPolicy: {{ .Values.pump.image.pullPolicy }}
        workingDir: "/opt/tyk-pump"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
        envFrom:
        - configMapRef:
            name: pump-env-conf-{{ include "tyk-headless.fullname" . }}
        env:
        {{ if .Values.redis.enableSentinel }}
        - name: TYK_PMP_ANALYTICSSTORAGECONFIG_SENTINELPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: redisSentinelPass
        {{- end }}
        - name: TYK_PMP_ANALYTICSSTORAGECONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: redisPass
        {{ if eq "postgres" (include "tyk-headless.backend" .) }}
        - name: TYK_PMP_PUMPS_MAIN_META_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: pgConnectionString
        - name: TYK_PMP_PUMPS_MAINAGG_META_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: pgConnectionString
        - name: TYK_PMP_UPTIMEPUMPCONFIG_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: pgConnectionString
        {{ else if eq "mongo" (include "tyk-headless.backend" .) }}
        - name: TYK_PMP_PUMPS_MAIN_META_MONGOURL
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: mongoURL
        - name: TYK_PMP_PUMPS_MAINAGG_META_MONGOURL
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: mongoURL
        - name: TYK_PMP_UPTIMEPUMPCONFIG_MONGOURL
          valueFrom:
            secretKeyRef:
              name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end }}
              key: mongoURL
        {{ end }}
        command: ["/opt/tyk-pump/tyk-pump", "-c", "/etc/tyk-pump/pump.conf"]
        volumeMounts:
          - name: tyk-pump-conf
            mountPath: /etc/tyk-pump
          {{- if .Values.pump.mounts }}
          {{- range $secret := .Values.pump.mounts }}
          - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
            mountPath: {{ $secret.mountPath }}
          {{- end }}
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: tyk-pump-conf
          configMap:
            name: pump-conf-{{ include "tyk-headless.fullname" . }}
            items:
              - key: pump.conf
                path: pump.conf
        {{- if .Values.pump.mounts }}
        {{- range $secret := .Values.pump.mounts }}
        - name: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
          secret:
            secretName: {{ $.Release.Name }}-pump-secret-{{ $secret.name }}
        {{- end }}
        {{- end }}
{{- end }}
