name: Release Helm charts

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: ["tyk-pro", "tyk-headless","tyk-hybrid"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3

      - name: Read helm chart version
        id: chart-values
        run: echo "::set-output name=version::$(awk '/version:/ {print $2}' ${{ matrix.repo }}/Chart.yaml)"

      - name: Package Helm chart
        run: helm package {{ matrix.repo }} --version ${{ steps.chart-values.outputs.version }}

#      - name: Push Helm chart
#        uses: cloudsmith-io/action@v0.5.2
#        with:
#          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
#          command: "push"
#          format: "helm"
#          owner: "tyk"
#          repo: "helm"
#          republish: "true"
#          file: "{{ matrix.repo }}-${{ steps.chart-values.outputs.version }}.tgz"
