name: Tyk Headless Push Helm
on: push
jobs:
  push:
    name: Tyk Headless Push CS
    runs-on: ubuntu-latest
    branches:
      - main
      - release-**
    paths:
      - 'tyk-headless/**'
    steps:
      - name: Install Helm, create dirs
        run: |
          echo "Installing Helm..."
          wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          tar -zxf helm-v${HELM_VERSION}-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version
        env:
          HELM_VERSION: "3.4.2"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pack helm artifact
        run: |
          output=$(helm package ${CHART} --version ${CHART_VERSION})
          echo $output
        env:
          CHART_VERSION: '0.0.0'
          CHART: tyk-headless

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'helm'
          owner: 'tyk'
          repo: 'tyk-headless'
          version: '0.0.0'
          file: './tyk-headless-0.0.0.tgz'
