name: Tyk Hybrid Push Helm
on: push
defaults:
  run:
    working-directory: ./tyk-hybrid
jobs:
  push:
    name: Tyk Hybrid Push CS
    runs-on: ubuntu-latest
    branches:
      - main
      - release-**
    paths:
      - 'tyk-hybrid/**'
    steps:
      - name: Install Helm, create dirs
        run: |
          echo "Installing Helm..."
          wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          tar -zxf helm-v${HELM_VERSION}-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version
          mkdir fixture
        env:
          HELM_VERSION: "3.4.2"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pack helm artifact
        run: |
          helm package ${CHART} -d ${CHART_DST} --version ${CHART_VERSION}
        env:
          CHART_VERSION: ${{ github.sha }}
          CHART: tyk-helm-chart/tyk-hybrid
          CHART_DST: './fixture'

      - uses: actions/checkout@v2

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'helm'
          owner: 'tyk'
          repo: 'tyk-hybrid'
          version: ${{ github.sha }}
          file: 'fixture/tyk-hybrid-${{ github.sha }}.tar.gz'
